import { Router } from "express";
import healthRoutes from "./health.routes";
import searchRoutes from "./search.routes";
import hotelsRoutes from "./hotels.routes";
import amenitiesRoutes from "./amenities.routes";
import roomFeaturesRoutes from "./room-features.routes";
import mealPlansRoutes from "./meal-plans.routes";
import recentSearchesRoutes from "./recent-searches.routes";
import searchSuggestionsRoutes from "./search-suggestions.routes";
import trendingDestinationsRoutes from "./trending-destinations.routes";
import favoritesRoutes from "./favorites.routes";
import bookingsRoutes from "./bookings.routes";
import paymentsRoutes from "./payments.routes";
import adminHotelsRoutes from "./admin/hotels.routes";
import adminAmenitiesRoutes from "./admin/amenities.routes";
import adminRoomTypesRoutes from "./admin/room-types.routes";
import adminRoomFeaturesRoutes from "./admin/room-features.routes";
import adminMealPlansRoutes from "./admin/meal-plans.routes";
import adminBookingsRoutes from "./admin/bookings.routes";
import adminDashboardRoutes from "./admin/dashboard.routes";
import internalBookingsRoutes from "./internal/bookings.routes";
import internalSearchRoutes from "./internal/search.routes";
import internalChatRoutes from "./internal/chat.routes";
import aiRoutes from "./ai.routes";

const router = Router();
router.use("/health", healthRoutes);
router.use("/search", searchRoutes);
router.use("/hotels", hotelsRoutes);
router.use("/amenities", amenitiesRoutes);
router.use("/room-features", roomFeaturesRoutes);
router.use("/meal-plans", mealPlansRoutes);
router.use("/recent-searches", recentSearchesRoutes);
router.use("/search-suggestions", searchSuggestionsRoutes);
router.use("/trending-destinations", trendingDestinationsRoutes);
router.use("/favorites", favoritesRoutes);
router.use("/bookings", bookingsRoutes);
router.use("/payments", paymentsRoutes);
router.use("/admin/hotels", adminHotelsRoutes);
router.use("/admin/amenities", adminAmenitiesRoutes);
router.use("/admin/room-types", adminRoomTypesRoutes);
router.use("/admin/room-features", adminRoomFeaturesRoutes);
router.use("/admin/meal-plans", adminMealPlansRoutes);
router.use("/admin/bookings", adminBookingsRoutes);
router.use("/admin/dashboard", adminDashboardRoutes);
router.use("/internal/bookings", internalBookingsRoutes);
router.use("/internal/search", internalSearchRoutes);
router.use("/internal/chat", internalChatRoutes);
router.use("/ai", aiRoutes);

export default router;
